# Generated by Django 5.1 on 2024-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_Id', models.CharField(max_length=200)),
                ('nome_leitor', models.CharField(max_length=200)),
                ('email_leitor', models.TextField(max_length=200)),
                ('endereco_leitor', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
