# Generated by Django 5.1 on 2024-09-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bliv_app', '0004_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitor',
            name='senha',
            field=models.CharField(default='12345678', max_length=16),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='book_data',
            field=models.JSONField(default=list),
        ),
    ]
